name: Publish Python distributions to PyPI

on: 
  push:
    branches: [main]

jobs:
  build-n-publish:
    name: Build and publish Python distributions PyPI
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          pip install -r requirements-test.txt

      - name: tests
        run: tox  

      - name: Build package
        run: python -m build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

